#%RAML 1.0
title: Craft online shopping
/product:
  get:
    queryParameters:
      name:
        type: string
        description: name of the product
        maxLength: 10
        required: false
        example: Dell
      Id: 
        type: integer
        description: id of the product
        required: false
        example: 1234
  /productid: 
   get:
   
/orders:
  get:
/catagory:
  get:
/users:
  get:
    
    
          